Challenge5
kzivanovic/Study-group pull request #8
Opened 2022-11-25 09:19 UTC by kzivanovic

2022-12-08 11:27 UTC, stefanworkco requested changes

2022-12-08 11:27 UTC, stefanworkco commented on cypress/support/commands.js
> +    cy.url().should('contains', 'inventory.html')
remove this check as assertion is not done in custom commands but in spec files

2022-12-08 11:27 UTC, stefanworkco commented on cypress/e2e/cart.cy.js
> +describe('Error with no data',()=>{
Refactor code to have just 1 describe with 4 it() (also use beforeEach in that case)

2022-12-08 11:27 UTC, stefanworkco commented on cypress/e2e/cart.cy.js
> +        cy.login('standard_user','secret_sauce')
when you add beforeEach, you don't need this line ( `cy.login('standard_user','secret_sauce')` ) here

2022-12-09 10:55 UTC, stefanworkco commented on cypress/e2e/cart.cy.js
> +        cy.login('standard_user','secret_sauce')
remove this since you already do this step in beforeEach (same in second it)

2022-12-09 10:58 UTC, stefanworkco commented on cypress/e2e/cart.cy.js
> +  it('Continue shopping',()=>{
extra it() wrapper

2022-12-09 10:58 UTC, stefanworkco approved these changes

2022-12-09 10:59 UTC, stefanworkco reviewed
Changes required

2022-12-09 11:08 UTC, stefanworkco approved these changes

2022-12-09 11:37 UTC, vesnaatwork approved these changes
👏

2022-12-09 12:37 UTC, tamaracvorovic-work approved these changes
👏 🎉

2022-12-09 13:17 UTC, merged